[package]
name = "yew-app"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.20.0", features = ["csr"] }
wasm-bindgen = "0.2"
web-sys = "0.3.60"
wasm-logger = "0.2.0"
log = "0.4.17"
