FROM rust:1.66.0-buster as chef
RUN cargo install cargo-chef
WORKDIR /app

FROM chef as planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef as cacher
COPY --from=planner /app/recipe.json recipe.json
RUN cargo chef cook --recipe-path recipe.json

FROM rust:1.66.0-buster as develop
WORKDIR /app
RUN rustup target add wasm32-unknown-unknown
RUN rustup component add clippy rustfmt
RUN wget -qO- https://github.com/thedodd/trunk/releases/download/v0.16.0/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
RUN cargo install --locked cargo-watch wasm-bindgen-cli
COPY --from=cacher /app/target target
CMD trunk serve --address 0.0.0.0 --port=8080
